spring:
  application:
    name: "test-application"
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver